"""在用户 PATH 已有的 ~/bin 目录里放置 topydo 全局命令入口（不修改注册表/PATH）。

两个 shim 全部使用纯 ASCII 内容，通过环境变量展开（%USERPROFILE% / $HOME）
定位实际 exe，避免 cmd.exe 按 OEM 代码页读取含中文路径的 .cmd 时出现乱码。
"""
import os
import stat

BIN = r"C:/Users/王佐成/bin"
REL = os.sep.join(["WorkBuddy", "todolist", ".venv-topydo", "Scripts", "topydo.exe"])

os.makedirs(BIN, exist_ok=True)

# 1) cmd.exe / PowerShell 用（%USERPROFILE% 由 cmd 原生展开，无编码问题）
cmd_shim = os.path.join(BIN, "topydo.cmd")
with open(cmd_shim, "w", encoding="ascii", newline="\r\n") as f:
    f.write("@echo off\r\n")
    f.write('"%USERPROFILE%' + os.sep + REL + '" %*\r\n')

# 2) Git Bash / MSYS 用
sh_shim = os.path.join(BIN, "topydo")
with open(sh_shim, "w", encoding="ascii", newline="\n") as f:
    f.write("#!/usr/bin/env bash\n")
    f.write("# topydo global entry (generated by WorkBuddy -> workspace venv)\n")
    f.write('exec "$HOME/WorkBuddy/todolist/.venv-topydo/Scripts/topydo.exe" "$@"\n')

os.chmod(sh_shim, os.stat(sh_shim).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

print("generated:")
for p in (cmd_shim, sh_shim):
    print("  %s  (%d bytes)" % (p, os.path.getsize(p)))
print("\n--- topydo.cmd ---")
print(open(cmd_shim, encoding="ascii").read())
print("--- topydo ---")
print(open(sh_shim, encoding="ascii").read())
